Args = --no-fallback \
       --enable-url-protocols=http,https \
       --report-unsupported-elements-at-runtime \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-run-time=io.github.mymonstercat.ocr.InferenceEngine \
       -H:+ReportExceptionStackTraces \
       --allow-incomplete-classpath
